python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16' --log_file='log1-1.txt' --seed=1 --resume_epoch=20 --test;
python GCAN-train.py --datasource='twitter16' --log_file='log1-2.txt' --fold_state=0;
python GCAN-train.py --datasource='twitter16' --log_file='log1-2.txt' --fold_state=1;
python GCAN-train.py --datasource='twitter16' --log_file='log1-2.txt' --fold_state=2;
python GCAN-train.py --datasource='twitter16' --log_file='log1-2.txt' --fold_state=3;
python GCAN-train.py --datasource='twitter16' --log_file='log1-2.txt' --fold_state=4;
python abml-GCAN.py --datasource='twitter16' --log_file='log2-1.txt' --seed=1 --data_scale=0.6;
python abml-GCAN.py --datasource='twitter16' --log_file='log2-1.txt' --seed=1 --data_scale=0.7;
python abml-GCAN.py --datasource='twitter16' --log_file='log2-1.txt' --seed=1 --data_scale=0.8;
python abml-GCAN.py --datasource='twitter16' --log_file='log2-1.txt' --seed=1 --data_scale=0.9;
python abml-GCAN.py --datasource='twitter16' --log_file='log2-1.txt' --seed=1 --data_scale=1.0;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.6 --resume_epoch=20 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.7 --resume_epoch=20 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.8 --resume_epoch=20 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=0.9 --resume_epoch=20 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log2-1.txt' --seed=1  --data_scale=1.0 --resume_epoch=20 --test;
python GCAN-train.py --datasource='twitter16' --log_file='log2-2.txt' --fold_state=1 --data_scale=0.6;
python GCAN-train.py --datasource='twitter16' --log_file='log2-2.txt' --fold_state=1 --data_scale=0.7;
python GCAN-train.py --datasource='twitter16' --log_file='log2-2.txt' --fold_state=1 --data_scale=0.8;
python GCAN-train.py --datasource='twitter16' --log_file='log2-2.txt' --fold_state=1 --data_scale=0.9;
python GCAN-train.py --datasource='twitter16' --log_file='log2-2.txt' --fold_state=1 --data_scale=1.0;
python abml-GCAN.py --datasource='twitter16' --log_file='log3-1.txt' --seed=1 --retweet_user_size=5;
python abml-GCAN.py --datasource='twitter16' --log_file='log3-1.txt' --seed=1 --retweet_user_size=10;
python abml-GCAN.py --datasource='twitter16' --log_file='log3-1.txt' --seed=1 --retweet_user_size=15;
python abml-GCAN.py --datasource='twitter16' --log_file='log3-1.txt' --seed=1 --retweet_user_size=20;
python abml-GCAN.py --datasource='twitter16' --log_file='log3-1.txt' --seed=1 --retweet_user_size=25;
python abml-GCAN.py --datasource='twitter16' --log_file='log3-1.txt' --seed=1 --retweet_user_size=30;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=5 --resume_epoch=20 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=10 --resume_epoch=20 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=15 --resume_epoch=20 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=20 --resume_epoch=20 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=25 --resume_epoch=20 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=1 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=2 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=3 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=4 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=5 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=6 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=7 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=8 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=9 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=10 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=11 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=12 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=13 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=14 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=15 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=16 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=17 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=18 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=19 --test;
python abml-GCAN.py --datasource='twitter16'  --log_file='log3-1.txt' --seed=1  --retweet_user_size=30 --resume_epoch=20 --test;
python GCAN-train.py --datasource='twitter16' --log_file='log3-2.txt' --fold_state=1 --retweet_user_size=5;
python GCAN-train.py --datasource='twitter16' --log_file='log3-2.txt' --fold_state=1 --retweet_user_size=10;
python GCAN-train.py --datasource='twitter16' --log_file='log3-2.txt' --fold_state=1 --retweet_user_size=15;
python GCAN-train.py --datasource='twitter16' --log_file='log3-2.txt' --fold_state=1 --retweet_user_size=20;
python GCAN-train.py --datasource='twitter16' --log_file='log3-2.txt' --fold_state=1 --retweet_user_size=25;
python GCAN-train.py --datasource='twitter16' --log_file='log3-2.txt' --fold_state=1 --retweet_user_size=30;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=1 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=2 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=3 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=4 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=5 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=6 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=7 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=8 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=9 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=10 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=11 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=12 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=13 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=14 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=15 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=16 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=17 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=18 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=19 --test;
python abml-GCAN_without_z.py --datasource='twitter16' --log_file='log5-1.txt' --seed=1 --resume_epoch=20 --test;
